#!/bin/bash

echo "[CloneAndInitializeRepo] - Starting "

mkdir /work && cd /work

echo "[CloneAndInitializeRepo] - clone repository "
git clone https://github.com/$REPO_OWNER/$REPO_NAME.git

echo "[CloneAndInitializeRepo] - verify previus commit "
if [ -n "${{ github.event.before }}" ] && [ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]; then
    git fetch --no-tags origin "${{ github.event.before }}" --depth 1 || true
fi

echo "[CloneAndInitializeRepo] - getting current commit "
git fetch --no-tags origin "${{ github.sha }}" --depth 1

git checkout --detach "${{ github.sha }}"

echo "RESULT_NAME=x86_64-glibc" >> "$GITHUB_ENV"
echo "base=${{github.event.before}}" >> "$GITHUB_OUTPUT"
echo "tip=${{github.sha}}" >> "$GITHUB_OUTPUT"

echo "[CloneAndInitializeRepo] - Finish "
