#!/bin/bash

echo "[MergeAndEditShlibs] - Starting process"

echo "[MergeAndEditShlibs] - clone xbps-src ..."
cd /work
git clone --depth 1 https://github.com/void-linux/void-packages.git void-packages
cd void-packages
git checkout --detach master
echo "[MergeAndEditShlibs] - clone xbps-src OK"

echo "[MergeAndEditShlibs] - copying templates ..."
cp -vr work/srcpkgs/* void-packages/srcpkgs/
echo "[MergeAndEditShlibs] - copying templates OK"

echo "[MergeAndEditShlibs] - update common shlibs ..."
local SHLIBS_FILE="void-packages/common/shlibs"
local APPEND_FILE="work/common/shlibs"
local REMOVE_FILE="work/shlibs_remove"

if [ -f "$REMOVE_FILE" ]; then
    while IFS= read -r line; do
        [ -z "$line" ] && continue # Verifying if the string line is empty
        grep -vF "$line" "$SHLIBS_FILE" > "$SHLIBS_FILE.tmp" && mv "$SHLIBS_FILE.tmp" "$SHLIBS_FILE"
        echo "[MergeAndEditShlibs] - RemovedLine: ${line} from ${REMOVE_FILE} "
    done < "$REMOVE_FILE"
fi

if [ -f "$APPEND_FILE" ]; then
    while IFS= read -r line; do
        [ -z "$line" ] && continue # Verifying if the string line is empty
        
        if ! grep -qF "$line" "$SHLIBS_FILE"; then
            echo "$line" >> "$SHLIBS_FILE"
            echo "[MergeAndEditShlibs] - AddedLine: ${line} to ${SHLIBS_FILE}"
        fi
    done < "$APPEND_FILE"
fi

echo "[MergeAndEditShlibs] - AddedLine: ${line} to ${SHLIBS_FILE}"

echo "[MergeAndEditShlibs] - applying inline edits..."
if [ -d "void-packages/srcpkgs/hyprutils/patches" ]; then
    echo "[MergeAndEditShlibs] - removing void-packages/srcpkgs/hyprutils/patches"
    rm -rf void-packages/srcpkgs/hyprutils/patches
fi

echo "[MergeAndEditShlibs] - update common shlibs OK"
