#!/bin/bash

set -e


echo "[PrepareAndBuild] - Starting prepare and build ..."
export PATH="/opt/xbps/usr/bin/:$PATH"

# Entry on right repo
cd /work/void-packages

changedpackages="$CHANGEDPACKAGES"
removedpackages="$REMOVEDPACKAGES"

if [ -z "${changedpackages}" ] && [ -z "${removedpackages}" ]; then
    echo "[PrepareAndBuild] - Nothing has changed, exiting"
    exit 0
fi


if [ -n "$changedpackages" ]; then
    echo "[PrepareAndBuild] - Changed packages: ${changedpackages}"
    PKGS=$(sudo -Eu builder ./xbps-src sort-dependencies $changedpackages)
else
    echo "[PrepareAndBuild] - No changed packages, skipping build"
    PKGS=""
fi

failed=""
built=""

echo "[PrepareAndBuild] - Building packages: ${PKGS}"
for pkg in $PKGS; do
    
    if sudo -Eu builder ./xbps-src -j"$(nproc)" pkg "${pkg}"; then
        echo "[PrepareAndBuild] - Successfully built ${pkg}"
        built="${built} ${pkg}"
    else
        echo "[PrepareAndBuild] - !! build failed for ${pkg}"
        failed="${failed} ${pkg}"
    fi
done


if [ -n "${failed}" ]; then
    echo "[PrepareAndBuild] - build of following packages failed:"
    for f in ${failed}; do
        echo "[PrepareAndBuild] - ${f}"
    done
    exit 1
fi

echo "[PrepareAndBuild] - Starting prepare and build OK"
