#!/bin/bash

set -e

echo "[RemoveOldFiles] - Actual dir => $(pwd)"

echo "[RemoveOldFiles] - Set git variables"
BRANCH="repository-$RESULT_NAME"
REMOTE="https://$REPO_OWNER:$ACCESS_GIT@github.com/$REPO_OWNER/$REPO_NAME.git"

echo "[RemoveOldFiles] - creating temporary dir for old branch"
mkdir -p /tmp/oldrepo

echo "[RemoveOldFiles] - creating temporary dir for new packages"
mkdir -p /tmp/newpkgs

echo "[RemoveOldFiles] - move new packages to temp dir"
mv -v ./*.xbps /tmp/newpkgs 2> /dev/null || true
mv -v ./*.xbps.sig /tmp/newpkgs 2> /dev/null || true

echo "[RemoveOldFiles] - remove all files in ${pwd}"
rm -rf ./*

echo "[RemoveOldFiles] - copy new packages to temp dir"
if git ls-remote --exit-code --heads "$REMOTE" "$BRANCH" >/dev/null 2>&1; then
    echo "[RemoveOldFiles] - Cloning remote repository"
    git clone --depth 1 --branch "$BRANCH" "$REMOTE" /tmp/oldrepo

    echo "[RemoveOldFiles] - Copy oldrepo binpkgs"
    cp -v /tmp/oldrepo/*.xbps ./ 2> /dev/null || true
    cp -v /tmp/oldrepo/*.xbps.sig ./ 2> /dev/null || true
    cp -v /tmp/oldrepo/index* ./ 2> /dev/null || true

    if [ -d "/tmp/oldrepo" ] && [ -n "$(ls -A /tmp/oldrepo)" ]; then

       echo "[RemoveOldFiles] - Delete rebuilded packages"
    
       for f in /tmp/newpkgs/*.xbps; do
            [ -e "$f" ] || continue
            base=$(basename "$f")
            # pkgname = everything before the first -<digit>
            pkgname=$(printf "%s\n" "$base" | sed -E 's/-[0-9].*$//')
            # remove all versions/revisions of that package from current repo dir
            echo "[RemoveOldFiles] - Removing ${pkgname} file"
            rm -f "${pkgname}-"*.xbps "${pkgname}-"*.xbps.sig 2>/dev/null || true
       done

       echo "[RemoveOldFiles] - Delete removed packages"

       if [ -n "$REMOVEDPACKAGES" ]; then
            echo "[RemoveOldFiles] - Delete packages that template no longer exists"

            for pkg in $REMOVEDPACKAGES; do
                rm -f "${pkg}*.xbps" 2> /dev/null || true
                rm -f "${pkg}*.xbps.sig" 2> /dev/null || true
                echo "[RemoveOldFiles] - Remove ${pkg} file"
            done 
       fi
    fi
fi;

echo "[RemoveOldFiles] - Move back the new packages to binpkgs"
mv -v /tmp/newpkgs/*.xbps /work/void-packages/hostdir/binpkgs  2> /dev/null || true
mv -v /tmp/newpkgs/*.xbps.sig  /work/void-packages/hostdir/binpkgs 2> /dev/null || true
