#!/bin/bash
set -e

echo "[IndexPackages] - Starting "

cd /work/void-packages/hostdir/binpkgs

echo "[IndexPackages] - Current Dir => ${pwd} "

# Generate repository index if we have artifacts
if ls ./*.xbps >/dev/null 2>&1; then
    echo "[IndexPackages] - Indexing Packages"
    sudo -Eu builder xbps-rindex -a *.xbps
else
    echo "[IndexPackages] - No packages to index; skipping xbps-rindex"
fi

echo "[IndexPackages] - Finish "

