#!/bin/bash
#
set -e

echo "[SignPackages] - Sign Packages"

cd /work


echo "[SignPackages] - Download .pem"

curl -H "Authorization: token $PEM_PAT" \
     -H 'Accept: application/vnd.github.v3.raw' \
     -O -L https://api.github.com/repos/$REPO_OWNER/vur-pem/contents/private.pem
     
echo "[SignPackages] - Downloaded .pem"

# Sign packages
if ls /work/packages/*.xbps >/dev/null 2>&1; then
    sudo -Eu builder xbps-rindex --privkey /work/private.pem --sign --signedby \"$REPO_NAME-github-action\" /work/packages
    sudo -Eu builder xbps-rindex --privkey /work/private.pem --sign-pkg /work/packages/*.xbps
else
    echo "[SignPackages] - No packages to sign; skipping xbps-rindex"
fi
