#!/bin/bash

set -e

cd /work/$REPO_NAME

echo "[PushToRepository] - Actual dir => $(pwd)"

# Config
echo "[PushToRepository] - Configuring git user"
git config user.name \"github-actions[bot]\"
git config user.email \"github-actions[bot]@users.noreply.github.com\"

# Populate and push new binary repository
echo "[PushToRepository] - Populating and pushing new binary repository"

if [ ! -d "/work/packages" ] || [ -z "$(ls -A /work/packages)" ]; then
    echo "[PushToRepository] - No packages found, skipping push to repository"
else
    echo "[PushToRepository] - Adding files"
    cp -vr /work/packages/* ./
    git add .
    git commit -m \"Upload latest packages to repository\" || true
    git push -f https://$REPO_OWNER:$ACCESS_GIT@github.com/$REPO_OWNER/$REPO_NAME.git repository-$RESULT_NAME || true

fi

echo "[PushToRepository] - Done"
