#!/bin/bash

set -e

echo "[PushToRepository] - Actual dir => $(pwd)"

# Config
echo "[PushToRepository] - Configuring git user"
git config user.name \"github-actions[bot]\"
git config user.email \"github-actions[bot]@users.noreply.github.com\"

# Delete old binary repository, create new one
echo "[PushToRepository] - Deleting old binary repository"
git push https://$REPO_OWNER:$ACCESS_GIT@github.com/$REPO_OWNER/$REPO_NAME.git -d repository-$RESULT_NAME
git switch --orphan repository-$RESULT_NAME

# Populate and push new binary repository
echo "[PushToRepository] - Populating and pushing new binary repository"
cp -vr /work/packages/* ./

echo "[PushToRepository] - Adding files"
git add .
git commit -m \"Upload latest packages to repository\"
git push -f https://$REPO_OWNER:$ACCESS_GIT@github.com/$REPO_OWNER/$REPO_NAME.git repository-$RESULT_NAME

echo "[PushToRepository] - Done"
