#!/bin/bash
set -e

echo "[SignPackages] - Sign Packages"

cd /work/void-packages/hostdir/binpkgs

echo "[IndexPackages] - Current Dir => ${pwd} "

echo "[SignPackages] - Download .pem"

curl -H "Authorization: token $PEM_PAT" \
     -H 'Accept: application/vnd.github.v3.raw' \
     -L https://api.github.com/repos/$REPO_OWNER/vur-pem/contents/private.pem \
     -o /tmp/private.pem
     
echo "[SignPackages] - Downloaded .pem"

# Sign packages
if ls ./*.xbps >/dev/null 2>&1; then
    xbps-rindex --privkey /tmp/private.pem --sign --signedby \"$REPO_NAME-github-action\" ./
    xbps-rindex --privkey /tmp/private.pem --sign-pkg ./*.xbps
else
    echo "[SignPackages] - No packages to sign; skipping xbps-rindex"
fi
