#!/usr/bin/env sh

COMMAND="
  cd /work
  git clone --depth 1 https://github.com/void-linux/void-packages.git

  cd /work/$REPO_NAME
  cat common/shlibs >> /work/void-packages/common/shlibs


  #swap packages from this repo into void-packages
  for package in $(find /work/$REPO_NAME/srcpkgs -maxdepth 1 -mindepth 1 -type d -printf '%f\n'); do
    echo \"Removing upstream package: $package\"
    rm -rf /work/void-packages/srcpkgs/$package
    echo \"Copying local package: $package\"
    cp -vr /work/$REPO_NAME/srcpkgs/$package /work/void-packages/srcpkgs
  done

  # List all files to verify
  echo 'Contents of /work/void-packages/srcpkgs/:'
  ls -la /work/void-packages/srcpkgs/

  chown -R builder:builder /work

  cd /work/void-packages
  sudo -Eu builder common/travis/set_mirror.sh &&
  sudo -Eu builder common/travis/prepare.sh &&
  common/travis/fetch-xtools.sh
"

echo "Running command: $COMMAND"
sh -c "$COMMAND"

