#!/usr/bin/bash
# Clone void-packages and prepare it by swapping in local packages
cd /work
git clone --depth 1 https://github.com/void-linux/void-packages.git

# set shlibs
cd /work/$REPO_NAME
cat common/shlibs >> /work/void-packages/common/shlibs

#swap packages from this repo into void-packages
for package in $(find /work/$REPO_NAME/srcpkgs -maxdepth 1 -mindepth 1 -type d -printf '%f\n'); do
  echo \"Removing upstream package: $package\"
  rm -rf /work/void-packages/srcpkgs/$package
  echo \"Copying local package: $package\"
  cp -vr /work/$REPO_NAME/srcpkgs/$package /work/void-packages/srcpkgs
done

# List all files to verify
echo 'Contents of /work/void-packages/srcpkgs/:'
ls -la /work/void-packages/srcpkgs/

# Ensure correct permissions
chown -R builder:builder /work
# Prepare void-packages
cd /work/void-packages
sudo -Eu builder common/travis/set_mirror.sh &&
sudo -Eu builder common/travis/prepare.sh &&

#fetch xbps-src xtools
common/travis/fetch-xtools.sh
